### ISSUE TITLE
Framerate Drop When Looking at Doors

### ISSUE THREAD

**Issue by Sinuousity** [ColeDeanShepherd/TESUnity#20]
Issue is due to unnecessary rebuilding and setting of the active state of the interactTextObj Text mesh.
Also impacted by using GetComponent<Text>() to find the Text component every frame.

Will be fixed by caching a reference to the Text component on interactTextObj and only activating or deactivating interactTextObj when necessary.

**Comment by Sinuousity** [comment]
Fixed on my fork.

**Comment by ColeDeanShepherd** [comment]
Thanks Sinuousity, feel free to make a pull request if you'd like. If not, I'll check out your fork later and incorporate the changes.

**Comment by Sinuousity** [comment]
I'm still new to GitHub / Repositories, so forgive me if I do things a little incorrectly or just don't know what to do. I'll put in the pull request, though.

**Comment by ColeDeanShepherd** [comment]
I've merged your pull request. Thanks again for all your great work! By the way, I added support for big endian CPUs in a commit last night, you should incorporate it into your fork!
