### ISSUE TITLE
Cell's names are empty with the French edition of Morrowind

### ISSUE THREAD

**Issue by demonixis** [ColeDeanShepherd/TESUnity#29]
Hi, 

I've just cloned the repository to test it with my French installation of Morrowind. At the first start, I have not textures on meshes and the player is falling. 

![image](https://cloud.githubusercontent.com/assets/1017126/19019163/e220be56-887c-11e6-8842-795cab4bb749.png)

After a bit of debugging, I have found that the method `SpawnPlayerInside(string interiorCellName, Vector3 position)` can't finish it's job because `dataReader.FindInteriorCellRecord(interiorCellName)` and `CreateInteriorCell(interiorCellName)` returns `false`.

In the function `public CELLRecord FindInteriorCellRecord(string cellName)`, the value of `CELL.NAME.value` is empty for all cells, as you can see on the screenshot

![image](https://cloud.githubusercontent.com/assets/1017126/19019139/d5d6eda6-887b-11e6-86a6-985c7ab43f60.png)

How can I help you to fix that? I'll try to fix it by myself, but you've maybe an idea that can helps me?

Thanks.

**Comment by ColeDeanShepherd** [comment]
Hey, thanks for opening the issue, and I'm sorry you're having this problem.

Someone else has emailed me with similar issues with another version of Morrowind, I think the problem is that Morrowind has different versions of its ESM file format and my ESM loading code doesn't support all of them for some reason (it should).

To debug this, I would add some breakpoints [in here](https://github.com/ColeDeanShepherd/TESUnity/blob/master/Assets/Scripts/TES/ESMFile.cs#L1803) and figure out where things are going wrong. It probably won't be an easy bug to find, unfortunately...

I would debug it myself, but as of now I am absurdly busy. If you want, you can send me your "Data Files/Morrowind.esm" file and I'll try to take a look this weekend.

**Comment by demonixis** [comment]
Hi,

Thanks for your help and thanks for this awesome project. I was able to fix that in my branch [here](https://github.com/demonixis/TESUnity). My branch has full VR support and other enhancements. If you're interested, I can create a [pull request](https://github.com/ColeDeanShepherd/TESUnity/compare/master...demonixis:VRMode).

**Comment by ColeDeanShepherd** [comment]
That would be great! It looks like you've made a lot of progress on your branch, I'd love to merge it in.

Just wondering, do you have any issues when you enter interior cells?

**Comment by demonixis** [comment]
That's perfect, I wanted to release a new version of my branch tonight, but I'll prepare a pull request too :)

The only issue I have with interior cells is the water which is sometime spawned to the bad place. Sometime the water is not required (Houses in Balmora).

About my branch, that's what I have done
- Created some new methods
- Added a full gamepad support (it's usefull in VR)
- Added full VR support for Oculus Rift and SteamVR (Vive)
- Added a Config.ini file for some parameters (lights, rendering path, etc...)

I'm working on a new MaterialManager which can use more shader types. The current Shader is not compatible with Unity 5.5 but with my work, we can use every types of shaders and the user can configure that in a Config.ini file. The MWUnlitMaterial and the MWBumpedDiffuseMaterial have very good results. But it's not yet finished.

My pull request will not contains this work, except if you want to work on it ;)

You can see TESUnityVR in video [here](https://www.youtube.com/watch?v=ojIvwxKcbDc)

**Comment by ColeDeanShepherd** [comment]
Alright, I'll look into the water issue.

The MaterialManager is something I've been meaning to refactor for a while. Thanks for your help on that, I might work on it as well and make a pull request in your fork.

Also, I'd still like to look at your Morrowind.esm file, the cell names shouldn't be empty! Could you send me that through an email or maybe skype at cole@coledeanshepherd.com?

Thanks again for taking the time to prepare a pull request. Don't worry about making it perfect, I need to refactor a lot of code anyways.

**Comment by demonixis** [comment]
Hi,

It'll takes a little more time because I have a bug in the latest build (not the editor, all is fine in the editor) and I want to fix it.

I'll contact you by email for more informations ;)
