### ISSUE TITLE
Add underwater effects.

### ISSUE THREAD

**Issue by ColeDeanShepherd** [ColeDeanShepherd/TESUnity#5]

**Comment by demonixis** [comment]
Hi, I'm working on this effect, I'm trying to implement [this one](https://alastaira.wordpress.com/2014/10/07/underwater-effects/). For now I've the blue fog effect (which is not very nice) but I'll a projector and maybe few particles. The main problem is that the water prefab is not double sided.  

Edit:  I have a good result!

![image](https://cloud.githubusercontent.com/assets/1017126/19147088/bf641646-8bb6-11e6-86dc-181c308efe0f.png)

Edit 2: A PR has been submited #33

**Comment by ColeDeanShepherd** [comment]
Looks great! Thank you!
